workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: CarnivOS API Key
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: com.CarnivOS.app
      node: 22
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          # Always create fresh iOS project for consistency
          rm -rf ios
          npx cap add ios
          echo "=== Directory structure after cap add ios ==="
          ls -la ios/
          ls -la ios/App/ || echo "ios/App not found"
          echo "=== Running cap sync ==="
          npx cap sync ios
          echo "=== Directory structure after cap sync ==="
          ls -la ios/App/
          cat ios/App/Podfile || echo "Podfile not found"
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          echo "=== Current directory contents ==="
          ls -la
          pod install
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo 0)
          agvtool new-version -all $((LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - sibuketu@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
